/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by scripts/extract-template-settings.ts
 */

export type InferredFieldType = 
  'text' | 'textarea' | 'number' | 'checkbox' | 'color' | 'image' | 'url' | 'json'
;

export type InferredField = {
  key: string;
  label: string;
  type: InferredFieldType;
  defaultValue?: unknown;
};

export const GENERATED_TEMPLATE_DEFAULTS: Record<string, Record<string, unknown>> = {
  "baby": {
    "banner_url": "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=2000&q=80",
    "store_name": "BabyOS",
    "template_browse_by_category_label": "Browse by category",
    "template_buy_now_label": "Buy Now",
    "template_empty_category_text": "No items in this category",
    "template_featured_kicker": "Soft & snuggly picks",
    "template_featured_product_label": "Featured product",
    "template_featured_text": "A small edit of plush toys, blankets and first outfits designed to feel soft against newborn skin. Gentle colors, cozy textures, and everyday comfort.",
    "template_featured_title": "Plush friends and warm layers.",
    "template_footer_suffix": "Modern Baby Store",
    "template_grid_kicker": "All baby products",
    "template_grid_title": "Pieces in this universe",
    "template_header_cart_label": "Cart (0)",
    "template_header_search_label": "Search",
    "template_hero_badge_left": "New season",
    "template_hero_badge_right": "Soft & Playful",
    "template_hero_heading": "A soft, modern universe\nfor every little moment.",
    "template_hero_image_alt": "Baby hero",
    "template_hero_subtitle": "Toys, outfits, feeding essentials, nursery finds and tiny gifts — curated for newborns and toddlers in one balanced, playful store.",
    "template_items_suffix": "items",
    "template_primary_cta": "Shop baby essentials",
    "template_product_badge_1": "Soft",
    "template_product_badge_2": "0–6m",
    "template_secondary_cta": "View all toys"
  },
  "bags": {},
  "beauty": {
    "store_name": "BloomSkin",
    "template_hero_heading": "A clean, modern beauty store built around routines, concerns and shades",
    "template_hero_subtitle": "Filter by skin concern, routine time, product type and price. Wishlist your favorites and explore base shades."
  },
  "cafe": {
    "store_name": "Sweet Home Dz"
  },
  "electronics": {
    "store_name": "ElectroVerse"
  },
  "fashion": {
    "banner_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
    "store_name": "WardrobeOS",
    "template_button_text": "Browse collection",
    "template_hero_heading": "Build a wardrobe that behaves like software.",
    "template_hero_subtitle": "Fewer pieces, more combinations. Coats, trousers, and layers designed to work in any city, any season."
  },
  "fashion2": {
    "store_name": "LineaWear",
    "template_button_text": "Shop Now",
    "template_hero_heading": "Build a fashion store that feels like a campaign, but behaves like a clean, modern catalog."
  },
  "fashion3": {
    "store_name": "LineaWear",
    "template_button_text": "Explore",
    "template_hero_heading": "Premium Essentials"
  },
  "food": {},
  "jewelry": {
    "banner_url": "https://images.unsplash.com/photo-1603561596112-0a132b757133?auto=format&fit=crop&w=1600&q=80",
    "store_name": "JewelryOS",
    "template_edit_image_1": "https://images.unsplash.com/photo-1617038688874-ef666027625a?auto=format&fit=crop&w=900&q=80",
    "template_edit_image_1_alt": "Gold detail 1",
    "template_edit_image_2": "https://images.unsplash.com/photo-1611003228941-98852ba62227?auto=format&fit=crop&w=900&q=80",
    "template_edit_image_2_alt": "Gold detail 2",
    "template_edit_subtitle_1": "Sculpted rings and chains in warm 18K gold. Soft light, precise edges and a focus on proportion.",
    "template_edit_subtitle_2": "Each piece is designed to stack quietly or stand alone.",
    "template_edit_title": "The Gold Edit",
    "template_empty_hint": "Products will appear automatically once you add them to your store.",
    "template_empty_subtitle": "Add your jewelry pieces to see them displayed here.",
    "template_empty_title": "No Products Yet",
    "template_footer_suffix": "Minimal Luxury Jewelry",
    "template_grid_count_suffix": "pieces",
    "template_grid_title": "Pieces in this collection",
    "template_hero_cta": "Explore the collection",
    "template_hero_heading": "Timeless jewelry, designed in gold and light.",
    "template_hero_image_alt": "Hero jewelry",
    "template_hero_kicker": "Gold & silver jewelry / 2025",
    "template_hero_subtitle": "A focused collection of rings, bracelets, necklaces and earrings in 18K gold, silver and diamonds. Built for quiet luxury, worn every day.",
    "template_highlight_label": "Highlight piece",
    "template_nav_bag": "Bag (0)",
    "template_nav_collections": "Collections",
    "template_nav_engagement": "Engagement",
    "template_nav_gold": "Gold",
    "template_nav_search": "Search",
    "template_view_piece_label": "View piece"
  },
  "perfume": {
    "banner_url": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1600&q=80",
    "store_name": "Premium Scents",
    "template_all_scents_title": "All Scents",
    "template_buy_now_label": "Buy Now",
    "template_editorial_1_text": "Built for night-heavy rooms. Amber, smoke, and vanilla crafted to leave a trail of warmth and mystery.",
    "template_editorial_1_title": "Realm I — Noir Extrait",
    "template_editorial_2_text": "Bright, structured, and modern. Neroli, citrus, and musk for clean daytime presence.",
    "template_editorial_2_title": "Realm II — Golden Luxe",
    "template_editorial_3_text": "Minimal, airy, and skin-like. Soft musks and woods that feel like a second skin.",
    "template_editorial_3_title": "Realm III — Dreamscape",
    "template_empty_hint": "Products will appear automatically once you add them to your store.",
    "template_empty_subtitle": "Add fragrances to your store to see them displayed here.",
    "template_empty_title": "No Fragrances Yet",
    "template_explore_more_title": "Explore More",
    "template_featured_title": "Featured",
    "template_filter_all_label": "All",
    "template_filter_dark_label": "Noir",
    "template_filter_dream_label": "Dream",
    "template_filter_gold_label": "Gold",
    "template_footer_rights": "All rights reserved.",
    "template_hero_heading": "A New Way to Experience Scent",
    "template_hero_subtitle": "Three realms. One universe. Discover fragrances crafted for mood, presence, and identity."
  },
  "store": {
    "banner_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1400&auto=format&fit=crop",
    "currency_code": "DZD",
    "store_name": "ElectroStore DZ",
    "template_button_text": "Build Your PC",
    "template_hero_heading": "Your Trusted Electronics Store",
    "template_hero_subtitle": "Shop smartphones, laptops, monitors, and configure your dream PC with expert-curated parts and local support.",
    "template_neon_color": "#00f0ff",
    "template_slide2_cta_text": "Shop Now",
    "template_slide2_subtitle": "High performance products for every need.",
    "template_slide2_title": "Featured Collection"
  }
};

export const GENERATED_TEMPLATE_FIELDS: Record<string, InferredField[]> = {
  "baby": [
    {
      "defaultValue": "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=2000&q=80",
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "defaultValue": "BabyOS",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "key": "template_age_chips",
      "label": "Age Chips",
      "type": "text"
    },
    {
      "defaultValue": "Browse by category",
      "key": "template_browse_by_category_label",
      "label": "Browse By Category Label",
      "type": "text"
    },
    {
      "defaultValue": "Buy Now",
      "key": "template_buy_now_label",
      "label": "Buy Now Label",
      "type": "text"
    },
    {
      "key": "template_categories_json",
      "label": "Categories Json",
      "type": "text"
    },
    {
      "defaultValue": "No items in this category",
      "key": "template_empty_category_text",
      "label": "Empty Category Text",
      "type": "text"
    },
    {
      "defaultValue": "Soft & snuggly picks",
      "key": "template_featured_kicker",
      "label": "Featured Kicker",
      "type": "text"
    },
    {
      "defaultValue": "Featured product",
      "key": "template_featured_product_label",
      "label": "Featured Product Label",
      "type": "text"
    },
    {
      "defaultValue": "A small edit of plush toys, blankets and first outfits designed to feel soft against newborn skin. Gentle colors, cozy textures, and everyday comfort.",
      "key": "template_featured_text",
      "label": "Featured Text",
      "type": "text"
    },
    {
      "defaultValue": "Plush friends and warm layers.",
      "key": "template_featured_title",
      "label": "Featured Title",
      "type": "text"
    },
    {
      "key": "template_footer_links",
      "label": "Footer Links",
      "type": "url"
    },
    {
      "defaultValue": "Modern Baby Store",
      "key": "template_footer_suffix",
      "label": "Footer Suffix",
      "type": "textarea"
    },
    {
      "defaultValue": "All baby products",
      "key": "template_grid_kicker",
      "label": "Grid Kicker",
      "type": "text"
    },
    {
      "defaultValue": "Pieces in this universe",
      "key": "template_grid_title",
      "label": "Grid Title",
      "type": "text"
    },
    {
      "defaultValue": "Cart (0)",
      "key": "template_header_cart_label",
      "label": "Header Cart Label",
      "type": "text"
    },
    {
      "defaultValue": "Search",
      "key": "template_header_search_label",
      "label": "Header Search Label",
      "type": "text"
    },
    {
      "defaultValue": "New season",
      "key": "template_hero_badge_left",
      "label": "Hero Badge Left",
      "type": "text"
    },
    {
      "defaultValue": "Soft & Playful",
      "key": "template_hero_badge_right",
      "label": "Hero Badge Right",
      "type": "text"
    },
    {
      "defaultValue": "A soft, modern universe\nfor every little moment.",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Baby hero",
      "key": "template_hero_image_alt",
      "label": "Hero Image Alt",
      "type": "image"
    },
    {
      "defaultValue": "Toys, outfits, feeding essentials, nursery finds and tiny gifts — curated for newborns and toddlers in one balanced, playful store.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    },
    {
      "defaultValue": "items",
      "key": "template_items_suffix",
      "label": "Items Suffix",
      "type": "text"
    },
    {
      "defaultValue": "Shop baby essentials",
      "key": "template_primary_cta",
      "label": "Primary Cta",
      "type": "text"
    },
    {
      "defaultValue": "Soft",
      "key": "template_product_badge_1",
      "label": "Product Badge 1",
      "type": "text"
    },
    {
      "defaultValue": "0–6m",
      "key": "template_product_badge_2",
      "label": "Product Badge 2",
      "type": "text"
    },
    {
      "defaultValue": "View all toys",
      "key": "template_secondary_cta",
      "label": "Secondary Cta",
      "type": "text"
    }
  ],
  "bags": [
    {
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    }
  ],
  "beauty": [
    {
      "defaultValue": "BloomSkin",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "key": "template_concerns",
      "label": "Concerns",
      "type": "text"
    },
    {
      "defaultValue": "A clean, modern beauty store built around routines, concerns and shades",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Filter by skin concern, routine time, product type and price. Wishlist your favorites and explore base shades.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    }
  ],
  "cafe": [
    {
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "key": "store_city",
      "label": "Store City",
      "type": "text"
    },
    {
      "defaultValue": "Sweet Home Dz",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    }
  ],
  "electronics": [
    {
      "defaultValue": "ElectroVerse",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    }
  ],
  "fashion": [
    {
      "defaultValue": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "defaultValue": "WardrobeOS",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "Browse collection",
      "key": "template_button_text",
      "label": "Button Text",
      "type": "text"
    },
    {
      "key": "template_genders",
      "label": "Genders",
      "type": "text"
    },
    {
      "defaultValue": "Build a wardrobe that behaves like software.",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Fewer pieces, more combinations. Coats, trousers, and layers designed to work in any city, any season.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    }
  ],
  "fashion2": [
    {
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "key": "store_description",
      "label": "Store Description",
      "type": "textarea"
    },
    {
      "defaultValue": "LineaWear",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "Shop Now",
      "key": "template_button_text",
      "label": "Button Text",
      "type": "text"
    },
    {
      "key": "template_genders",
      "label": "Genders",
      "type": "text"
    },
    {
      "defaultValue": "Build a fashion store that feels like a campaign, but behaves like a clean, modern catalog.",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    }
  ],
  "fashion3": [
    {
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "key": "store_description",
      "label": "Store Description",
      "type": "textarea"
    },
    {
      "defaultValue": "LineaWear",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "Explore",
      "key": "template_button_text",
      "label": "Button Text",
      "type": "text"
    },
    {
      "key": "template_genders",
      "label": "Genders",
      "type": "text"
    },
    {
      "defaultValue": "Premium Essentials",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    }
  ],
  "food": [
    {
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    }
  ],
  "jewelry": [
    {
      "defaultValue": "https://images.unsplash.com/photo-1603561596112-0a132b757133?auto=format&fit=crop&w=1600&q=80",
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "defaultValue": "JewelryOS",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "https://images.unsplash.com/photo-1617038688874-ef666027625a?auto=format&fit=crop&w=900&q=80",
      "key": "template_edit_image_1",
      "label": "Edit Image 1",
      "type": "image"
    },
    {
      "defaultValue": "Gold detail 1",
      "key": "template_edit_image_1_alt",
      "label": "Edit Image 1 Alt",
      "type": "image"
    },
    {
      "defaultValue": "https://images.unsplash.com/photo-1611003228941-98852ba62227?auto=format&fit=crop&w=900&q=80",
      "key": "template_edit_image_2",
      "label": "Edit Image 2",
      "type": "image"
    },
    {
      "defaultValue": "Gold detail 2",
      "key": "template_edit_image_2_alt",
      "label": "Edit Image 2 Alt",
      "type": "image"
    },
    {
      "defaultValue": "Sculpted rings and chains in warm 18K gold. Soft light, precise edges and a focus on proportion.",
      "key": "template_edit_subtitle_1",
      "label": "Edit Subtitle 1",
      "type": "textarea"
    },
    {
      "defaultValue": "Each piece is designed to stack quietly or stand alone.",
      "key": "template_edit_subtitle_2",
      "label": "Edit Subtitle 2",
      "type": "textarea"
    },
    {
      "defaultValue": "The Gold Edit",
      "key": "template_edit_title",
      "label": "Edit Title",
      "type": "text"
    },
    {
      "defaultValue": "Products will appear automatically once you add them to your store.",
      "key": "template_empty_hint",
      "label": "Empty Hint",
      "type": "text"
    },
    {
      "defaultValue": "Add your jewelry pieces to see them displayed here.",
      "key": "template_empty_subtitle",
      "label": "Empty Subtitle",
      "type": "textarea"
    },
    {
      "defaultValue": "No Products Yet",
      "key": "template_empty_title",
      "label": "Empty Title",
      "type": "text"
    },
    {
      "key": "template_footer_links",
      "label": "Footer Links",
      "type": "url"
    },
    {
      "defaultValue": "Minimal Luxury Jewelry",
      "key": "template_footer_suffix",
      "label": "Footer Suffix",
      "type": "textarea"
    },
    {
      "defaultValue": "pieces",
      "key": "template_grid_count_suffix",
      "label": "Grid Count Suffix",
      "type": "text"
    },
    {
      "defaultValue": "Pieces in this collection",
      "key": "template_grid_title",
      "label": "Grid Title",
      "type": "text"
    },
    {
      "defaultValue": "Explore the collection",
      "key": "template_hero_cta",
      "label": "Hero Cta",
      "type": "text"
    },
    {
      "defaultValue": "Timeless jewelry, designed in gold and light.",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Hero jewelry",
      "key": "template_hero_image_alt",
      "label": "Hero Image Alt",
      "type": "image"
    },
    {
      "defaultValue": "Gold & silver jewelry / 2025",
      "key": "template_hero_kicker",
      "label": "Hero Kicker",
      "type": "text"
    },
    {
      "defaultValue": "A focused collection of rings, bracelets, necklaces and earrings in 18K gold, silver and diamonds. Built for quiet luxury, worn every day.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    },
    {
      "key": "template_hero_tags",
      "label": "Hero Tags",
      "type": "text"
    },
    {
      "defaultValue": "Highlight piece",
      "key": "template_highlight_label",
      "label": "Highlight Label",
      "type": "text"
    },
    {
      "defaultValue": "Bag (0)",
      "key": "template_nav_bag",
      "label": "Nav Bag",
      "type": "text"
    },
    {
      "defaultValue": "Collections",
      "key": "template_nav_collections",
      "label": "Nav Collections",
      "type": "text"
    },
    {
      "defaultValue": "Engagement",
      "key": "template_nav_engagement",
      "label": "Nav Engagement",
      "type": "text"
    },
    {
      "defaultValue": "Gold",
      "key": "template_nav_gold",
      "label": "Nav Gold",
      "type": "text"
    },
    {
      "defaultValue": "Search",
      "key": "template_nav_search",
      "label": "Nav Search",
      "type": "text"
    },
    {
      "defaultValue": "View piece",
      "key": "template_view_piece_label",
      "label": "View Piece Label",
      "type": "text"
    }
  ],
  "perfume": [
    {
      "defaultValue": "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1600&q=80",
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "defaultValue": "Premium Scents",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "All Scents",
      "key": "template_all_scents_title",
      "label": "All Scents Title",
      "type": "text"
    },
    {
      "defaultValue": "Buy Now",
      "key": "template_buy_now_label",
      "label": "Buy Now Label",
      "type": "text"
    },
    {
      "defaultValue": "Built for night-heavy rooms. Amber, smoke, and vanilla crafted to leave a trail of warmth and mystery.",
      "key": "template_editorial_1_text",
      "label": "Editorial 1 Text",
      "type": "text"
    },
    {
      "defaultValue": "Realm I — Noir Extrait",
      "key": "template_editorial_1_title",
      "label": "Editorial 1 Title",
      "type": "text"
    },
    {
      "defaultValue": "Bright, structured, and modern. Neroli, citrus, and musk for clean daytime presence.",
      "key": "template_editorial_2_text",
      "label": "Editorial 2 Text",
      "type": "text"
    },
    {
      "defaultValue": "Realm II — Golden Luxe",
      "key": "template_editorial_2_title",
      "label": "Editorial 2 Title",
      "type": "text"
    },
    {
      "defaultValue": "Minimal, airy, and skin-like. Soft musks and woods that feel like a second skin.",
      "key": "template_editorial_3_text",
      "label": "Editorial 3 Text",
      "type": "text"
    },
    {
      "defaultValue": "Realm III — Dreamscape",
      "key": "template_editorial_3_title",
      "label": "Editorial 3 Title",
      "type": "text"
    },
    {
      "defaultValue": "Products will appear automatically once you add them to your store.",
      "key": "template_empty_hint",
      "label": "Empty Hint",
      "type": "text"
    },
    {
      "defaultValue": "Add fragrances to your store to see them displayed here.",
      "key": "template_empty_subtitle",
      "label": "Empty Subtitle",
      "type": "textarea"
    },
    {
      "defaultValue": "No Fragrances Yet",
      "key": "template_empty_title",
      "label": "Empty Title",
      "type": "text"
    },
    {
      "defaultValue": "Explore More",
      "key": "template_explore_more_title",
      "label": "Explore More Title",
      "type": "text"
    },
    {
      "defaultValue": "Featured",
      "key": "template_featured_title",
      "label": "Featured Title",
      "type": "text"
    },
    {
      "defaultValue": "All",
      "key": "template_filter_all_label",
      "label": "Filter All Label",
      "type": "text"
    },
    {
      "defaultValue": "Noir",
      "key": "template_filter_dark_label",
      "label": "Filter Dark Label",
      "type": "text"
    },
    {
      "defaultValue": "Dream",
      "key": "template_filter_dream_label",
      "label": "Filter Dream Label",
      "type": "text"
    },
    {
      "defaultValue": "Gold",
      "key": "template_filter_gold_label",
      "label": "Filter Gold Label",
      "type": "text"
    },
    {
      "defaultValue": "All rights reserved.",
      "key": "template_footer_rights",
      "label": "Footer Rights",
      "type": "textarea"
    },
    {
      "defaultValue": "A New Way to Experience Scent",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Three realms. One universe. Discover fragrances crafted for mood, presence, and identity.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    }
  ],
  "store": [
    {
      "defaultValue": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1400&auto=format&fit=crop",
      "key": "banner_url",
      "label": "Banner Url",
      "type": "image"
    },
    {
      "defaultValue": "DZD",
      "key": "currency_code",
      "label": "Currency Code",
      "type": "text"
    },
    {
      "defaultValue": "ElectroStore DZ",
      "key": "store_name",
      "label": "Store Name",
      "type": "text"
    },
    {
      "defaultValue": "Build Your PC",
      "key": "template_button_text",
      "label": "Button Text",
      "type": "text"
    },
    {
      "key": "template_default_dark",
      "label": "Default Dark",
      "type": "text"
    },
    {
      "defaultValue": "Your Trusted Electronics Store",
      "key": "template_hero_heading",
      "label": "Hero Heading",
      "type": "text"
    },
    {
      "defaultValue": "Shop smartphones, laptops, monitors, and configure your dream PC with expert-curated parts and local support.",
      "key": "template_hero_subtitle",
      "label": "Hero Subtitle",
      "type": "textarea"
    },
    {
      "defaultValue": "#00f0ff",
      "key": "template_neon_color",
      "label": "Neon Color",
      "type": "color"
    },
    {
      "defaultValue": "Shop Now",
      "key": "template_slide2_cta_text",
      "label": "Slide2 Cta Text",
      "type": "text"
    },
    {
      "defaultValue": "High performance products for every need.",
      "key": "template_slide2_subtitle",
      "label": "Slide2 Subtitle",
      "type": "textarea"
    },
    {
      "defaultValue": "Featured Collection",
      "key": "template_slide2_title",
      "label": "Slide2 Title",
      "type": "text"
    }
  ]
};
